apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: admin-service
  name: admin-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: admin-service
    spec:
      containers:
        - image: weeranh/admin-service
          name: admin-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources: {}
status: {}
